INSERT INTO authors (nameFirst, nameLast, id) VALUES ("Bram", "Stoker", 1);
INSERT INTO authors (nameFirst, nameLast, id) VALUES ("Oscar", "Wilde", 2);
INSERT INTO authors (nameFirst, nameLast, id) VALUES ("Alice", "Walker", 3);
INSERT INTO authors (nameFirst, nameLast, id) VALUES ("Leo", "Tolstoy", 4);
INSERT INTO authors (nameFirst, nameLast, id) VALUES ("Charles", "Dickens", 5);
INSERT INTO authors (nameFirst, nameLast, id) VALUES ("Arthur", "Miller", 6);
INSERT INTO authors (nameFirst, nameLast, id) VALUES ("Alexandre", "Dumas", 7);
INSERT INTO authors (nameFirst, nameLast, id) VALUES ("Arthur Conan", "Doyle", 8);
INSERT INTO authors (nameFirst, nameLast, id) VALUES ("Robert Louis", "Stevenson", 9);
INSERT INTO authors (nameFirst, nameLast, id) VALUES ("Fyodor", "Dostoyevsky", 10);
INSERT INTO authors (nameFirst, nameLast, id) VALUES ("Agatha", "Christie", 11);
INSERT INTO authors (nameFirst, nameLast, id) VALUES ("Ray", "Bradbury", 12);
INSERT INTO authors (nameFirst, nameLast, id) VALUES ("George", "Orwell", 13);
INSERT INTO authors (nameFirst, nameLast, id) VALUES ("H.G.", "Wells", 14);
INSERT INTO authors (nameFirst, nameLast, id) VALUES ("Chinua", "Achebe", 15);